# Generated by Django 3.2.12 on 2022-02-22 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(help_text='Should be entered, year-month-day')),
                ('company_name', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('telephone', models.CharField(blank=True, max_length=100)),
                ('bidding_settings', models.CharField(choices=[('HI', 'High'), ('ME', 'Medium'), ('LO', 'Low')], default='HI', max_length=2)),
                ('google_ads_account_id', models.CharField(blank=True, max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
